CREATE TABLE temperature_readings ( id BIGINT GENERATED BY  
  DEFAULT AS IDENTITY PRIMARY KEY, temperature NUMERIC NOT NULL, date DATE NOT NULL, 
  time TIME NOT NULL, created_at TIMESTAMP WITH TIME ZONE DEFAULT
  timezone('utc'::text, now()) NOT NULL );
